/*
 * generated by Xtext 2.12.0
 */
package de.david_wille.bibtexconsistencychecker.consistencyrule.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class BCCConsistencyRuleUiModule extends AbstractBCCConsistencyRuleUiModule {
}
