/*
 * generated by Xtext 2.12.0
 */
package de.david_wille.bibtexconsistencychecker.bibtex.ide


/**
 * Use this class to register ide components.
 */
class BCCBibTeXIdeModule extends AbstractBCCBibTeXIdeModule {
}
