/*
 * generated by Xtext 2.12.0
 */
package de.david_wille.bibtexconsistencychecker.consistencyrule


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BCCConsistencyRuleStandaloneSetup extends BCCConsistencyRuleStandaloneSetupGenerated {

	def static void doSetup() {
		new BCCConsistencyRuleStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
