/*
 * generated by Xtext 2.12.0
 */
package de.david_wille.bibtexconsistencychecker.bibtex


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class BCCBibTeXRuntimeModule extends AbstractBCCBibTeXRuntimeModule {
}
