/*
 * generated by Xtext 2.12.0
 */
package de.david_wille.bibtexconsistencychecker.bibtex


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BCCBibTeXStandaloneSetup extends BCCBibTeXStandaloneSetupGenerated {

	def static void doSetup() {
		new BCCBibTeXStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
