/*
 * generated by Xtext 2.12.0
 */
package de.david_wille.bibtexconsistencychecker.consistencyrule.ide


/**
 * Use this class to register ide components.
 */
class BCCConsistencyRuleIdeModule extends AbstractBCCConsistencyRuleIdeModule {
}
