/*
 * generated by Xtext 2.12.0
 */
package de.david_wille.bibtexconsistencychecker.executionmodel


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BCCExecutionModelStandaloneSetup extends BCCExecutionModelStandaloneSetupGenerated {

	def static void doSetup() {
		new BCCExecutionModelStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
